apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset
spec:
  selector:
    matchLabels:
      app: sample-app
  serviceName: sample-statefulset
  replicas: 4
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.16
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G
